### ISSUE TITLE
`rake test` fails with FFI::NotFoundError

### ISSUE THREAD

**Issue by paddor** [mtortonesi/ruby-czmq-ffi#2]
Hi

I'm thinking about using this gem. Looking through the code, I saw quite a few TODOs and when running `rake test`, I get this:

```
$ rake test
/Users/paddor/.rubies/ruby-2.2.3/bin/ruby -I"lib:test"  "/Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/zframe_test.rb"
/Users/paddor/.gem/ruby/2.2.3/gems/ffi-1.9.10/lib/ffi/library.rb:261:in `attach_function': Function 'zmsg_dump' not found in [/usr/local/lib/libczmq.dylib] (FFI::NotFoundError)
    from /Users/paddor/ruby-czmq-ffi/lib/czmq-ffi/libczmq.rb:152:in `<module:LibCZMQ>'
    from /Users/paddor/ruby-czmq-ffi/lib/czmq-ffi/libczmq.rb:3:in `<top (required)>'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/ruby-czmq-ffi/lib/czmq-ffi.rb:4:in `<top (required)>'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/ruby-czmq-ffi/test/test_helper.rb:4:in `<top (required)>'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/ruby-czmq-ffi/test/zframe_test.rb:1:in `<top (required)>'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:15:in `block in <main>'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `select'
    from /Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test"  "/Users/paddor/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/zframe_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

Seems like `zmsg_dump` doesn't exist anymore (I'm using the most recent version of CZMQ, version 3.0.2).

So, in other words, is this project production ready?

**Comment by paddor** [comment]
The same applies for `zloop_set_tolerant`.

**Comment by paddor** [comment]
Seems like this project is dead. I'm coming up with my own [CZMQ binding](https://github.com/paddor/cztop).
